#+TITLE: 2017 -2018 年度总结、计划

距离 2017 年过去已经有一周时间了，因为最近忙着写签报的时间，所有现在才有时间做总结。

总体来说，2017 年在我的人生中是一个转折点，虽然不知道这样做在以后看来对不对、理不理智，但是，我现在绝不后悔！

下面从 2017 年总结和今年的计划两个方面进行总结。
* 2017 年总结

下面从优点和不足两个大方面对 2017 年的学习、工作、生活进行总结。

** 学习方面
*** 积极因素

- 写了 2 篇论文

2017 年，在工作之余，主笔或参与写了 2 篇小文章，分别是《
2016 年度中央水利建设投资计划执行情况简要分析 》《最严格水资源管理制度实施背景下工业用水效率的影响因素研究》，均发表在《水利发展研究》杂志。

- 读了若干书籍和文章

今年阅读了易中天先生的《青春志》、《从春秋到战国》、《三国纪》、《魏晋风度》、《南朝、北朝》，还读了《中华的崩溃与扩大：魏晋南北朝》、沈复的《浮生六记》、《月亮与六便士》《万历十五年》《邓小平传》《鲁迅全集第二卷》《毛泽东第一卷》，也看了金庸小说《鸳鸯刀》《连城诀》《碧血剑》，粗粗翻阅了《利用 python 开展数据分析》。

今年通过 zotero 软件阅读了 30-40 篇了银行信用风险的文献。

- 态度更积极、计划更清晰

说来也惭愧，到了 17 年年底对照人赵浩的学习主动性，才发觉自己的学习习惯过于懒散，用毛主席的话说就是自由主义惯了。通过在知乎网站上看学习方法，利用 wunderlist、pomotodo 等软件，自己的学习更有主动性了，学习计划更详细，学习效果比以前更好了。

*** 消极因素
- 文章数量、质量还有提升空间

虽然写了 2 篇文章，但是老实说文章质量不好，还有很大的提升空间，希望今年写更多的文章。

- 专业书籍阅读量不够

去年读了很多杂书，统计、金融专业书籍阅读量不够，希望今年阅读更多的专业书籍。

- 学习总结还不够

自己已掌握了一些学习方法，但是发现读过的书、文章很多时候会忘了核心内容，这就说明总结的还不够，再学习的力度不够，不会抓重点。

- 学习计划还不够详细

目前，常常觉得晚上和周末学习工作的热情不高，自己反省了一下，觉得还是自己学习计划的不够详细。希望今年能够改变这一现状。

- 思考不够

古人说过，学而不思则罔，就是说一味读书而不思考，就会因为不能深刻理解书本的意义而不能合理有效利用书本的知识，甚至会陷入迷茫。自己时常觉得自己读的书，就是咀嚼不够，没有充分吸收书本的知识要点，读书对我更像是完成一项任务，而非享受。

希望在今后的学习过程中，要加强思考，无论是从书本中还是工作、生活中。最好每天花了半小时想想自己一天的所得所失。

** 工作方面

工作方面，今年最大的一个变化就是从水利部发展研究中心辞职，进了中国人民银行征信中心做了博后。

目前，也不好说这个决定是理智还是任性，但是不后悔。人不能做自己不喜欢的事情，我可以暂时做不喜欢的工作，但是不能一辈子都在那种环境下读过。

回顾自己水利部的工作，自己的文字能力得到了加强，一些好的写作习惯和经验养成了，但是自己想做学术意愿不再那么强烈。下面说说不足。

*** 消极因素
- 工作专业能力要加强

发现自己对工作缺少一种专研的精神，特别是对自己不喜欢的工作更是有一种敷衍，停留在表面的工作态度，希望在今后的工作中要狠下决心专研工作。这一块也是有很多诀窍的，包括学会问同事、专研资料，要养成这么一种习惯，在遇到不同的问题的时候，要自己先去发现答案，从而引申到生活里面，遇到不同人交流时，要多思考我与这人之间有没有什么问题需要问他，或者需要获得什么信息，什么东西都要多想想。

- 计划执行力度不够、制定的不够详细

我发现遇到自己不喜欢的工作或者觉得很难开展的工作会有拖延现象，思索了固然有懒惰的心态在作祟，但是还是计划没有做细，计划无法得到有效执行。

- 容易被其他事情干扰

还有一个缺点，自己在事情的时候，常常会遇到其他事情干扰，导致自己工作效率十分低下，无法及时完成当前工作。注意力不够集中，又犯了自由主义。希望今后加强注意力方面的训练。

** 生活方面
生活方面，一是自从换单位就把家从亚运村搬到了白广路，现在下班花费在路上的时间大大缩减，幸福感大大提升。家里最近添置了书架子和床头柜，幸福感进一步提升:-)。
二是办了一张健身卡，体重最近没有上升，血压下降了，但是最近去的次数少了，今后一定保持一周至少去 2 次。
三是感情方面，还是还是没有进展，希望尽快遇到一个好人吧。

* 2018 年计划

** 学习方面
*** 研究

今年至少阅读 100 篇信用风险相关文献，并保证发表 2 篇左右论文。

*** 书籍

至少保证阅读 30 本文学著作，精读 3-4 本专业书籍，泛读 10 本左右专业相关书籍。定期写阅读笔记。

** 工作方面

专研业务知识，了解一二代征信系统的相关细节，并有意识的出卷子自己做。对待工作一定要保持十分的热情和认真，再难的工作也要及时完成，不允许有拖延现象。

** 生活方面

认真生活，少熬夜，最好在 11 点之前睡觉，保证好睡眠，定期开展卫生大扫除。
